# Generated by Django 4.1 on 2023-04-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_scrapper", "0005_auto_20230217_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urls",
            name="url",
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name="NavURLS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element", models.CharField(max_length=255)),
                ("attribute", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navurls",
                        to="web_scrapper.urls",
                    ),
                ),
            ],
        ),
    ]
