# Generated by Django 4.1 on 2023-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scrapper", "0006_alter_urls_url_navurls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navurls",
            name="value",
            field=models.CharField(max_length=255555),
        ),
    ]
