# Generated by Django 4.1 on 2023-04-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_scrapper", "0007_alter_navurls_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navurls",
            old_name="attribute",
            new_name="navattribute",
        ),
        migrations.RenameField(
            model_name="navurls",
            old_name="element",
            new_name="navelement",
        ),
        migrations.RenameField(
            model_name="navurls",
            old_name="title",
            new_name="navtitle",
        ),
        migrations.RenameField(
            model_name="navurls",
            old_name="user",
            new_name="navuser",
        ),
        migrations.RenameField(
            model_name="navurls",
            old_name="value",
            new_name="navvalue",
        ),
    ]
